seL4/sel4test

apps/sel4test-tests/src/tests/inc_untyped.c
- This test will pass on current master, which always uses buffered
machine registers for syscalls
- It will fail if syscall_stub_gen.py is run without --buffer, as
the error descriptions are lost on the way through [1]
- It will pass once more when seL4/seL4#45 lands :-)
[1] http://sel4.systems/pipermail/devel/2016-October/001079.html
=> Check error descriptions during untyped tests

apps/sel4test-tests/src/tests/syscall.c
Just the basics to make sure the *WithMRs functions are exercised.
This is not expected to pass (or build!) until seL4/seL4#45 lands.
=> Basic tests for *WithMRs syscalls

tools/compile-all.sh
The environment variables from different runs affect compilation in the
compile-all target, which causes the compilation of some defconfigs to
fail. Fix by compiling each kernel_elf target in a clean environment.
=> Polluted environment when running make compile-all

apps/sel4test-driver/src/main.c
If an IRQ handler cannot be allocated for a driver, the failure should
be treated as an error rather than silently dropped.
Partial fix for #25
=> Catch and handle failure to allocate IRQ

apps/sel4test-driver/src/main.c
Recent changes to cpio library require use of
`const void *` now.
Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>
=> trivial: change cpio_get_file type

apps/sel4test-tests/src/tests/scheduler.c
The time provided to the tasks seems to be exhausted in some occasions before a task can yield on the ODROID-XU with the exynos5410 with debug enabled.
Doubling the budget should not affect periodic scheduling for this test.
Response time analysis for the task set give the following:
0 - WCET = 20us, min. inter-arrival = 100us, response time = 60us
1 - WCET = 20us, min. inter-arrival = 200us, response time = 80us
2 - WCET = 20us, min. inter-arrival = 800us, response time = 260us
Given the response time for each task is less than the inter-arrival time and they all execute at the same priority, they should settle into a regular schedule within the hyperperiod (800us).
=> Increase execution time for SCHED0014

apps/sel4test-tests/src/tests/faults.c
We must ensure that during the reset of the server in the timeout test that the client is not able to preempt the server. If it does, it can perform a send before the server performs a receive. If this occurs, the server will not be blocked when the test thread removes its scheduling context and the test will hang indefinitely.
=> Ensure server prio greater than client for timeout

apps/sel4test-tests/src/tests/schedcontext.c
https://github.com/seL4/sel4test/commit/4f37fac63bda3dfd21b27eec4bcdccb9f041d044 added the CONFIG_HAVE_TIMER macro, but it looks like there were some copy/paste errors for SCHED_CONTEXT_0010-0013.
=> Fix timer requirement for scheduling context tests

apps/sel4test-tests/arch/riscv/arch_frame_type.h
Rocketchip default platform configuration only has 256MB of RAM, so we can't allocate a huge 1GB page. For this reason, I included the check of CONFIG_PLAT_ROCKETCHIP for use huge page in frame tests. 
Also, I removed outdated platform configuration BUILD_ROCKET_CHIP_ZEDBOARD. The configuration CONFIG_BUILD_ROCKET_CHIP_ZEDBOARD was actually removed from the kernel on seL4/seL4@8b4ed99#diff-6633bf96e2f098e25816ecca9848a8de18e0041f704567699d2cbca62edf5058
=> riscv: disable huge page for rocketchip

apps/sel4test-tests/src/tests/cache.c
Reusing a frame object after revoking it and retyping it again shouldn't
see any old data from before the retype. The kernel should ensure that
any clear memory operations have been flushed completely out so that any
reads that bypass the caching hierarchy can't see old data.
Signed-off-by: Kent McLeod <kent@kry10.com>
=> CACHEFLUSH: Add test for flushing when retyping

apps/sel4test-driver/CMakeLists.txt, apps/sel4test-tests/src/tests/breakpoints.c, apps/sel4test-tests/src/tests/scheduler.c, settings.cmake
These are currently BREAKPOINT_002 and SCHED0021. The corresponding issues #43 and #42 remain open, and when resolved positively, these tests should be enabled again for simulation runs.
=> switch off tests that are flaky under simulation

apps/sel4test-tests/src/tests/scheduler.c
add missing return statement as fix https://github.com/seL4/sel4test/issues/47 for. @yyshen suggested just to return 0 here, but this seem to contradict what all other test are doing.
=> add missing return statement (fix #47)

apps/sel4test-tests/src/tests/scheduler.c
Resolves https://github.com/seL4/sel4test/issues/61
=> Resolve issues with SCHED0000 test

apps/sel4test-tests/src/tests/scheduler.c
Waiting for two timeouts is not enough when simulating in cloud
instances. Increase the timeout period under simulation to 100ms.
Signed-off-by: Kent McLeod <kent@kry10.com>
=> scheduler: Increase timeout period when simulating

apps/sel4test-tests/src/tests/faults.c
The unprivileged spec says the following:
We consider it a feature that any length of instruction containing all zero bits is not legal, as
this quickly traps erroneous jumps into zeroed memory regions. Similarly, we also reserve the
instruction encoding containing all ones to be an illegal instruction, to catch the other common
pattern observed with unprogrammed non-volatile memory devices, disconnected memory buses,
or broken memory devices.
Software can rely on a naturally aligned 32-bit word containing zero to act as an illegal
instruction on all RISC-V implementations, to be used by software where an illegal instruction
is explicitly desired. Defining a corresponding known illegal value for all ones is more difficult
due to the variable-length encoding. Software cannot generally use …
=> Use the reliable illegal instruction encoding

apps/sel4test-tests/src/tests/scheduler.c
When this test was introduced in commit beff0afd0bbb6d it requested 1 extra refill in each sched_context_configure call. These extra refills are not necessary to change the core/affinity of the SC and were probably an oversight.
The calls succeed when there is enough space in the SchedContext for at least 4 refills, but fail for 64 bit architectures with the now (seL4/seL4@bb6a00ffe25) tighter minimum SchedContext size where the minimum size works out to exactly 2 refills.
=> SCHED0022: do not request unnecessary refills

settings.cmake
The following command for building seL4test for the Spike (as documented here https://docs.sel4.systems/Hardware/spike.html) will not compile: `../init-build.sh -DPLATFORM=spike -DRISCV64=1`. This is because the CMake variable `SIMULATION` is not set so seL4test is trying to initialise a timer for the Spike, which isn't implemented. This patch turns `SIMULATION` on for the Spike by default, matching the behaviour for the QEMU AArch64 `virt` platform.
=> Set SIMULATION for Spike platform by default

settings.cmake
According to the comment in https://github.com/seL4/util_libs/pull/117 there is no `ltimer` implementation available. This change should avoid the need for https://github.com/seL4/ci-actions/pull/236
Test with: seL4/seL4#727, seL4/util_libs#117
=> disable timer test for Quartz64

domain_schedule.c, settings.cmake
We are currently not running any tests with NUM_DOMAINS > 1 and the defaults in sel4test lead to extremely slow test execution.
This PR picks nicer defaults:
- only 4 domains instead of 16
- give domain 0 a long time slice
- some schedule variety in the first 4 domains
- shortest period of 2 ticks
This should enable faster tests even under simulation.
This PR is a prerequisite for seL4/ci-actions#248.
=> better defaults for tests with NUM_DOMAINS > 1

.github/workflows/sel4test-hw.yml
This is a copy of the same pull request action from seL4/seL4.
Useful for checking if new tests are working on hardware.
=> github: enable hw-test and hw-build on PRs

apps/sel4test-tests/src/tests/faults.c
The fault assembly code manipulates an integer sized argument and so 32-bit register names need to be used in order to avoid compiler warnings.
=> aarch64: Use 32-bit sized register names

apps/sel4test-tests/src/tests/scheduler.c
The budgets in test SCHED0014 are the same, the periods are different (in relation 1/2/8), and we're checking that the kernel achieves that period relation in scheduling.
In this block in the function `test_ordering_periodic_threads`:
```c
set_helper_sched_params(env, &helpers[0], 20 * US_IN_MS, 100 * US_IN_MS, 0);
set_helper_sched_params(env, &helpers[1], 20 * US_IN_MS, 200 * US_IN_MS, 0);
set_helper_sched_params(env, &helpers[2], 20 * US_IN_MS, 800 * US_IN_MS, 0);
```
the first time parameter is the budget, the second is the period (not the other way around as the comment suggested).
=> SCHED0014: fix misleading comment

apps/sel4test-tests/src/tests/vspace.c
The aarch64 vspace API is changed to only have a single pagetable object and capability type for all intermediate page table levels. The root vspace object is still a separate object and capability type.
Test with: https://github.com/seL4/seL4/pull/801
Test with: https://github.com/seL4/seL4_libs/pull/59
=> aarch64: Minimal update for vspace API change

apps/sel4test-tests/src/main.c
libsel4utils/reserve_initial_task_regions iterates over existing_frames[] and expects it to be null-terminated. Without this commit, the behaviour will rely on whatever the stack had before allocating existing_frames[] in the stack, and subsequent calls may fail, hang, or reserve incorrect frames; depending on the stack values.
=> Fix: NULL-terminate existing_frames[] array

settings.cmake
The ltimer is not implemented for the rocket chip that runs on the ZCU102 FPGA. This disables the timer tests so sel4test can be built and run on this platform.
Helps fix issue: https://github.com/seL4/seL4/issues/1078
=> settings: Disable timer tests for RocketChipZCU102

apps/sel4test-driver/include/test_init_data.h, apps/sel4test-driver/src/testtypes.c, apps/sel4test-tests/src/main.c, apps/sel4test-tests/src/tests/smc.c
This new test will make sure that the SMC capability and its associated API call work as expected.
It tests the following:
1. A correctly configured call works
2. An SMC call with a function ID that uses a cap with a different badge fails
3. Minting an SMC cap from an SMC cap with a badge other than 0 fails
I tested this with the following configuration:
```
../init-build.sh -DPLATFORM=zcu102 -DRELEASE=true -DARM_HYP=TRUE -DKernelAllowSMCCalls=true
```
I wanted to test on QEMU, but it turned out to be non-trivial to integrate ATF with QEMU for sel4Test. It is doable, but I don't have the bandwidth to support it.
Note: This test assumes you are running ATF in EL3 on an AARCH64 platform. The successful test checks the standard service version and it reports back 0.1 (See …
=> Add tests for SMC Capability

apps/sel4test-tests/src/tests/scheduler.c
Decrease the chance that the monitor thread is preempted just when it has released the preemption threads, but before it has yielded itself. (If that happens, the preemption threads get two time slices.)
See also #42 -- the implementation here is basically @axel-h's suggestion from that issue.
We believe we might have seen an instance of this in one test run (of many) for PR seL4/seL4#968
=> SCHED0021: decrease chances of a race condition

apps/sel4test-tests/src/tests/smc.c
SMC caps are a new cap type for performing SMC calls on aarch64. These tests check that CNode operations behave as expected when manipulating capabilities of this type.
=> aarch64,smc: Add tests for SMC cap behaviors

apps/sel4test-tests/src/tests/smc.c
ATF implementations don't clobber x2 and x3 registers in response to ARM_STD_SVC_VERSION calls.
=> SMC0001: Remove test of clobbered registers

apps/sel4test-tests/src/tests/vcpu.c
This PR adds a test for a scenario described in https://github.com/seL4/seL4/issues/1199.
Using the following configuration:
`../init-build.sh -DPLATFORM=odroidc4 -DSMP=1 -DARM_HYP=1`
You will currently see the kernel crash:
```
KERNEL DATA ABORT!
Faulting instruction: 0x8000012d38
FAR: 0x3a8 ESR (DFSR): 0x96000004
halting...
Kernel entry via Syscall, number: 1, Call
Cap type: 15, Invocation tag: 48
```
This test is ARM specific. I believe there are no other vCPU tests in sel4test right now so I added a new file.
=> Add a test for injecting an IRQ on a vCPU without a TCB associated

settings.cmake
- in CMake, `INTERNAL` has the same effect as `FORCE`, so passing any `-DNANOPB_SRC_ROOT_FOLDER=...` to CMake on the command line will be overwritten and there is no way to customize the path then.
- the second commit removes the trailing slash of the variable, which seem more a cosmetic thing. Having a "//" on some paths in the variables that are created later seems not to cause any practical issues.
=> Allow setting NANOPB_SRC_ROOT_FOLDER 

apps/sel4test-driver/src/main.c, apps/sel4test-driver/src/tests/timer.c, apps/sel4test-driver/src/testtypes.c, apps/sel4test-driver/src/timer.c, apps/sel4test-tests/src/helpers.c, apps/sel4test-tests/src/main.c, apps/sel4test-tests/src/tests/ipc.c, apps/sel4test-tests/src/tests/schedcontext.c, apps/sel4test-tests/src/tests/scheduler.c
- remove explicit newline in `ZF_LOGx()`, the functions already prints a newline at the end.
- SCHED0003: log debug information instead of empty lines
=> remove explicit newline in ZF_LOGx()

apps/sel4test-tests/src/tests/fpu.c, apps/sel4test-tests/src/tests/ipc.c
config_set is true for 1 and false for all other values, so it does not make sense to use with CONFIG_MAX_NUM_NODES.
The two instances where this happened look like they are trying to guard CONFIG_MAX_NUM_NODES > 1 by checking whether CONFIG_MAX_NUM_NODES has any value at all, but doing so incorrectly. CONFIG_MAX_NUM_NODES has a default value of 1 and should always be set to a number, so we can just drop the guard. If this assumption about always having a numbers value is wrong, the code will not compile, which is acceptable.
Thanks to @jearc for spotting these.
This wrong setting has masked two SMP tests, which may now be failing.
=> use config_set only for boolean config values

apps/sel4test-tests/src/tests/scheduler.c
If we're seeing failures on this test, they need to be investigated. The resume invocation is definitely supposed to call the scheduler and leave with the highest priority thread running.
This "fix" was added before the release in 2014 and I don't have history copy of sel4test, so if anybody remembers what this might have been about, please do comment.
=> scheduler: resume does preempt

apps/sel4test-driver/src/tests/timer.c, apps/sel4test-tests/src/tests/faults.c, apps/sel4test-tests/src/tests/fpu.c, apps/sel4test-tests/src/tests/ipc.c, apps/sel4test-tests/src/tests/schedcontext.c, apps/sel4test-tests/src/tests/scheduler.c
This more than halves the time to run all tests.
=> Speedup Tests

apps/sel4test-tests/arch/riscv/arch_frame_type.h, settings.cmake
This PR adds build support for the Cheshire RISCV64 SoC. This system requires that huge page tests and the timer tests be disabled as the RAM is too small on the target FPGA (Digilent Genesys 2) and there are no hardware timers in Cheshire respectively. This PR requires the following PRs to merge before it can be used standalone:
https://github.com/seL4/seL4/pull/1354
https://github.com/seL4/util_libs/pull/188
=> Cheshire (CVA6) support

apps/sel4test-tests/src/tests/multicore.c, apps/sel4test-tests/src/tests/schedcontext.c, settings.cmake
Let's see if this fixes the recent new failures and the old ones for the disabled CI tests.
Would be nice to test this with https://github.com/seL4/ci-actions/pull/379, but no idea how to do that.
=> Replace volatiles with atomic for SMP tests

apps/sel4test-tests/src/tests/vspace.c
This *coincidentally* fails with ret == seL4_RevokeFirst(9) if the number of pools to allocate before failing is less than the actual amount, because we don't allocate a capability for the last pool.
In essence, that could be happening even if we had the correct number of pools, but doesn't because of how the kernel (presumably) checks that the cap is free after checking the ASID pools are free.
=> vspace004: allocate a cap for the final pool

apps/sel4test-tests/src/tests/vspace.c
This was working because ASIDPoolBits == PageBits on all existing platforms, but this might not always be the case.
=> vspace: use ASIDPoolBits for the ASIDPool untypes

apps/sel4test-driver/CMakeLists.txt, settings.cmake
This is a nonfunctional change, purely a decoupling of configs. Depends on https://github.com/seL4/util_libs/pull/196 to be merged first.
Test with: https://github.com/seL4/util_libs/pull/196
---
In libplatsupport, we know which platforms do not support an ltimer implementation, so rather than duplicating them, we can re-use the cmake config variable here.
However, this needs to be moved after util_libs_import_libraries() for the config to appear, but before config_option for it to be generated in the gen_config.h file.
I have tested this with:
- maaxboard (supports timer, tests enabled)
- zynqmp (supports timer, tests disabled)
- cheshire (no timer support, tests disabled)
=> ltimer: use platsupport export where it makes sense
